= Klinisk kontakt


== Metadata


TemplateId:: Arena-Cancer-HeadAndNeck-Reception-Journal_v45


Archetype:: openEHR-EHR-COMPOSITION.encounter.v1




:toc:




// Not supported rmType COMPOSITION
== EVENT_CONTEXT
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*EVENT_CONTEXT* + 
EVENT_CONTEXT: __
5+a|*Template versjonsinformasjon* + 
CLUSTER: _openEHR-EHR-CLUSTER.template_semver_dips.v1_
|at0001| 0..1| DV_CODED_TEXT | Navn
a|
* Oncology-Reception-Journal (no.dips.Oncology.HeadNeck.ReceptionJournal: Admission01)
5+a|*Semver* + 
CLUSTER: _at0003_
|at0004| 0..1| DV_COUNT | Major
|
|at0005| 0..1| DV_COUNT | Minor
|
|at0006| 0..1| DV_COUNT | Patch
|
|====
== Aktuelt
== Anamnese
== Aktuelt/Anamnese
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Aktuelt/Anamnese* + 
OBSERVATION: _openEHR-EHR-OBSERVATION.story.v1_
|at0004| 0..1| DV_TEXT | Anamnese
a|
5+a|*Reception note metadata dips* + 
CLUSTER: _openEHR-EHR-CLUSTER.reception_note_metadata_dips.v1_
|at0001| 0..*| DV_CODED_TEXT | Datakategori
a|
* at0005 -> Aktuelt 
|====
== Kontaktårsak/debuterende symptom
== Kartleggingsspørsmål om symptomer/sykdomstegn - første sympt
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Kartleggingsspørsmål om symptomer/sykdomstegn - første sympt* + 
OBSERVATION: _openEHR-EHR-OBSERVATION.symptom_sign_screening.v1_


Svarene kan være selvrapporterte.
|at0034| 0..1| DV_TEXT | Kartleggingsformål
a|
* hode- og halskreft


Dette dataelementet er ment for å sette en kontekst for spørsmålene om man senere ønsker å gjøre spørringer på dataene. Det er ikke forventet at dette dataelementet skal være synlig for en bruker av skjemaet, men kun tilgjengelig i de lagrede dataene. 
For eksempel: "Pre operativ screening" eller navnet på det faktiske spørreskjemaet.
5+a|*Første presenterende symptom/funn* + 
CLUSTER: _at0022_
|at0004| 1..1| DV_TEXT | Første presenterende symptom/funn
a|
* Smerte
* Kul på halsen
* Nerveutfall
* Vekttap
* Heshet/stridor
* Incidental radiologi
* Nesetetthet
* Annet


Navnet på symptom/sykdomstegn bør kodes med en terminologi om mulig.
|at0037| 0..1| DV_DATE_TIME | Tidsangivelse
|


Dataelementet "Tidsangivelse" er med hensikt løst modellert for å støtte ulike måter å angi tidsangivelser for symptomet eller sykdomstegnet i et spørreskjema. Den konkrete semantikken defineres i templatet. For eksempel: Symptomet eller sykdomstegnet faktiske dato og/eller klokkeslett, start- og sluttid for symptomet eller sykdomstegnet, et tidsintervall for når for symptomet eller sykdomstegnet oppstod, varigheten for symptomet eller sykdomstegnet, individets alder på tidspunktet symptomet eller sykdomstegnet oppstod, eller hvor lenge det siden det oppstod. Kan være en deldato, for eksempel bare år, ved å bruke datatypen DV_DATE_TIME.
5+a|*Symptom/Sykdomstegn* + 
CLUSTER: _openEHR-EHR-CLUSTER.symptom_sign.v1_
|at0001| 1..1| DV_TEXT | Vekttap
a|
* Vekttap


Navnet på symptom/sykdomstegn bør kodes med en terminologi om mulig.
|at0002| 0..1| DV_TEXT | Ev vekttap kg/tid
a|


Eksempel: "Svimmelhet med rotasjonsfølelse og av og til besvimelsesfølelse. Hurtig bevegelse fra sittende eller liggende til stående stilling virker å være en utløsende faktor. Opptrer typisk flere ganger daglig, og varer i ca et halvt til ett minutt hver gang. Å sette eller legge seg ned virker lindrende."
|at0035| 0..1| DV_TEXT | Kommentar
a|
|====
== Naturlige funksjoner
== Naturlige funksjoner
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Naturlige funksjoner* + 
OBSERVATION: _openEHR-EHR-OBSERVATION.progress_note.v1_
|at0004| 0..1| DV_TEXT | Naturlige funksjoner
a|
5+a|*Reception note metadata dips* + 
CLUSTER: _openEHR-EHR-CLUSTER.reception_note_metadata_dips.v1_
|at0001| 0..*| DV_CODED_TEXT | Datakategori
a|
* at0006 -> Naturlige funksjoner 
|====
== Medikamenter (husk legemiddelsamstemming, medikamenter skal oppdateres i kurve)
== Kartleggingsspørsmål om legemidler
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Kartleggingsspørsmål om legemidler* + 
OBSERVATION: _openEHR-EHR-OBSERVATION.medication_screening.v1_


Svarene kan være selvrapporterte.
// Not supported rmType POINT_EVENT
|at0040| 0..1| DV_TEXT | Kartleggingsformål
a|
* hode- og halskreft


Dette dataelementet er ment for å sette en kontekst for spørsmålene om man senere ønsker å gjøre spørringer på dataene. Det er ikke forventet at dette dataelementet skal være synlig for en bruker av skjemaet, men kun tilgjengelig i de lagrede dataene. 
For eksempel: "Preoperativ screening" eller navnet på det faktiske spørreskjemaet eller screening for tidligere bruk av en legemiddelklasse, som bisfosfonater.
|at0043| 0..1| DV_TEXT | Beskrivelse av medikamenter ved innkomst
a|
|undefined| 1..1| DV_DATE_TIME | Time
|
|====
== Kartlegging om allergi/cave - føres inn i kritisk info
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Kartlegging om allergi/cave - føres inn i kritisk info* + 
OBSERVATION: _openEHR-EHR-OBSERVATION.problem_screening.v1_


Svarene kan være selvrapporterte.
// Not supported rmType EVENT
|at0034| 0..1| DV_TEXT | Kartleggingsformål
a|
* hode- og halskreft


Dette dataelementet er ment for å sette en kontekst for spørsmålene, dersom man senere ønsker å gjøre spørringer på dataene. Det er ikke forventet at dette dataelementet skal være synlig for en bruker av skjemaet, men kun tilgjengelig i de lagrede dataene. For eksempel: "Preoperativ screening" eller navnet på det faktiske spørreskjemaet.
|at0028| 0..1| DV_CODED_TEXT | Har pasienten noen kjente allergier?
a|
* at0031 -> Ja 
* at0032 -> Nei 
* at0033 -> Ukjent 


Navnet på dataelementet kan omformuleres til det spesifikke spørsmålet i et templat eller brukergrensesnitt. Det foreslåtte verdisettet kan tilpasses/endres i det enkelte bruksområde ved å benytte de alternative datatypene DV_TEXT eller DV_BOOLEAN.
|at0028| 0..1| DV_BOOLEAN | Det er registrert i kritisk info til pasienten.
|


Navnet på dataelementet kan omformuleres til det spesifikke spørsmålet i et templat eller brukergrensesnitt. Det foreslåtte verdisettet kan tilpasses/endres i det enkelte bruksområde ved å benytte de alternative datatypene DV_TEXT eller DV_BOOLEAN.
|undefined| 1..1| DV_DATE_TIME | Time
|
|====
== Funksjonsstatus
== ECOG funksjonsstatus
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*ECOG funksjonsstatus* + 
OBSERVATION: _openEHR-EHR-OBSERVATION.ecog.v1_
|at0004| 1..1| DV_ORDINAL | ECOG funksjonsstatus
a|
* 0 - Asymptomatisk I stand til å utføre enhver normal aktivitet uten begrensning.
* 1 - Symptomatisk, fullt oppegående Ikke i stand til fysisk krevende aktivitet, men oppegående og i stand til å utføre lett arbeid.
* 2 - Symptomatisk, sengeliggende <50 % av våken tid Oppegående og i stand til all egenpleie, men ikke i stand til noe arbeid; oppe og i bevegelse mer enn 50% av våken tid.
* 3 - Symptomatisk, sengeliggende > 50 % av våken tid Bare i stand til begrenset egenpleie, bundet til seng eller stol > 50 % av våken tid.
* 4 - Helt sengeliggende Helt hjelpetrengende; klarer ikke noen egenpleie; helt bundet til seng eller stol.
* 5 - Død Pasienten er død.
|====
== Status presens
== Vitale målinger
== Høyde/Lengde
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Høyde/Lengde* + 
OBSERVATION: _openEHR-EHR-OBSERVATION.height.v2_


Høyde måles stående og lengde liggende.
|at0004| 1..1| DV_QUANTITY | Høyde (cm)
|
|====
== Kroppsvekt
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Kroppsvekt* + 
OBSERVATION: _openEHR-EHR-OBSERVATION.body_weight.v2_
|at0004| 1..1| DV_QUANTITY | Vekt (kg)
|
|====
== Kroppstemperatur
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Kroppstemperatur* + 
OBSERVATION: _openEHR-EHR-OBSERVATION.body_temperature.v2_
|at0004| 1..1| DV_QUANTITY | Temperatur (°C)
|
|at0066| 0..*| DV_TEXT | Konfunderende faktorer
a|
|====
== Pulsoksymetri
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Pulsoksymetri* + 
OBSERVATION: _openEHR-EHR-OBSERVATION.pulse_oximetry.v1_
// Not supported rmType DV_PROPORTION
|====
== Åndedrett
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Åndedrett* + 
OBSERVATION: _openEHR-EHR-OBSERVATION.respiration.v2_
|at0004| 1..1| DV_QUANTITY | Respirasjonsfrekvens (/min)
|
|====
== Blodtrykk
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Blodtrykk* + 
OBSERVATION: _openEHR-EHR-OBSERVATION.blood_pressure.v2_


Vanligvis brukes begrepet "blodtrykk" om måling av brakialt arterietrykk i overarmen.
|at0004| 1..1| DV_QUANTITY | Systolisk blodtrykk
|
|at0005| 1..1| DV_QUANTITY | Diastolisk blodtrykk
|
|====
== Puls/Hjertefrekvens
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Puls/Hjertefrekvens* + 
OBSERVATION: _openEHR-EHR-OBSERVATION.pulse.v2_
|at0004| 1..1| DV_QUANTITY | Hjertefrekvens (/min)
|


Det er spesifisert begrensninger i navn for å gjøre det lettere å eksplisitt merke dette elementet som Pulsfrekvens eller Hjertefrekvens ved behov.
|====
== Kroppsmasseindeks
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Kroppsmasseindeks* + 
OBSERVATION: _openEHR-EHR-OBSERVATION.body_mass_index.v2_
|at0004| 1..1| DV_QUANTITY | Kroppsmasseindeks
|
|====
== Kroppsoverflate
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Kroppsoverflate* + 
OBSERVATION: _openEHR-EHR-OBSERVATION.body_surface_area.v1_


Refereres også til som BSA (body surface area).
|at0004| 1..1| DV_QUANTITY | Kroppsoverflate
|


For eksempel: "1,81 m²".
|at0009| 0..1| DV_CODED_TEXT | Metode
a|
* at0010 -> Automatisk registrering 
|at0006| 0..1| DV_CODED_TEXT | Formel
a|
* at0012 -> Dubois og Dubois 
* at0013 -> Mosteller 
* at0014 -> Haycock 
* at0015 -> Gehan og George 
* at0016 -> Boyd 
* at0017 -> Fujimoto 
* at0018 -> Takihara 


For eksempel: Mosteller, DuBois og DuBois, Haycock og Boyd.
|====
// Not supported rmType ADMIN_ENTRY
5+a|*Kroppsoverflate referanse* + 
CLUSTER: _openEHR-EHR-CLUSTER.kroppsoverflate_referanse.v1_
|at0001| 0..1| DV_QUANTITY | Kroppsoverflate
|
5+a|*kroppsmasseindex referanse* + 
CLUSTER: _openEHR-EHR-CLUSTER.kroppsmasseindex_referanse.v1_
|at0001| 0..1| DV_QUANTITY | Kroppsmasseindex
|
5+a|*Høyde/Lengde referanse* + 
CLUSTER: _openEHR-EHR-CLUSTER.hoyde_referanse.v1_
|at0003| 0..1| DV_QUANTITY | Høyde/Lengde
|
|at0004| 0..1| DV_TEXT | Kroppstilling
a|
5+a|*Vekt referanse* + 
CLUSTER: _openEHR-EHR-CLUSTER.vekt_referanse.v1_
|at0003| 0..1| DV_QUANTITY | Kroppsvekt
|
|at0005| 0..1| DV_TEXT | Påkleding
a|
5+a|*Temperatur referanse* + 
CLUSTER: _openEHR-EHR-CLUSTER.kroppstemperatur_referanse.v1_
|at0001| 1..1| DV_QUANTITY | Temperatur
|
|at0003| 0..1| DV_CODED_TEXT | Målested
a|
5+a|*Respirasjon referanse* + 
CLUSTER: _openEHR-EHR-CLUSTER.respirasjon_referanse.v1_
|at0001| 0..1| DV_QUANTITY | Frekvens
|
|at0004| 0..1| DV_CODED_TEXT | Regelmessighet
a|
|at0005| 0..1| DV_CODED_TEXT | Dybde
a|
5+a|*Pulsoksymetri referanse* + 
CLUSTER: _openEHR-EHR-CLUSTER.pulsoksymetri_referanse.v1_
// Not supported rmType DV_PROPORTION
5+a|*Blodtrykk referanse* + 
CLUSTER: _openEHR-EHR-CLUSTER.blodtrykk_referanse.v1_
|at0001| 0..1| DV_QUANTITY | Systolisk
|
|at0002| 0..1| DV_QUANTITY | Diastolisk
|
|at0004| 0..1| DV_QUANTITY | Middelarterietrykk
|
|at0005| 0..1| DV_CODED_TEXT | Stilling
a|
5+a|*Pulse referanse* + 
CLUSTER: _openEHR-EHR-CLUSTER.pulse_referanse.v1_
|at0001| 0..1| DV_QUANTITY | Pulsfrekvens
|
|at0003| 0..1| DV_CODED_TEXT | Rytme
a|
// Not supported rmType CODE_PHRASE
// Not supported rmType CODE_PHRASE
// Not supported rmType PARTY_PROXY
== Status presens fritekst
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Status presens fritekst* + 
OBSERVATION: _openEHR-EHR-OBSERVATION.progress_note.v1_
|at0004| 0..1| DV_TEXT | Status presens
a|
5+a|*Reception note metadata dips* + 
CLUSTER: _openEHR-EHR-CLUSTER.reception_note_metadata_dips.v1_
|at0001| 0..*| DV_CODED_TEXT | Datakategori
a|
* at0010 -> Status presens 
|====
== Fysisk undersøkelse
== Funn ved Cor/Pulm undersøkelse
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Funn ved Cor/Pulm undersøkelse* + 
OBSERVATION: _openEHR-EHR-OBSERVATION.exam.v1_
|at0004| 0..1| DV_TEXT | Funn ved Cor/Pulm undersøkelse
a|


Kan anvendes til å registrere en tekstlig sammenfatning av en komplett klinisk undersøkelse eller nøkkelfunn ved den kliniske undersøkelsen, som vil bli understøttet av strukturerte data. Dette dataelementet kan brukes for å fange opp "legacy data" som ikke er tilgjengelig i et strukturert format. Detaljer om spesifikt strukturert funn inkluderes ved å bruke CLUSTER-arketyper i "Examination Detail" SLOT.
|====
== Funn ved ØNH undersøkelse
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Funn ved ØNH undersøkelse* + 
OBSERVATION: _openEHR-EHR-OBSERVATION.exam.v1_
|at0004| 0..1| DV_TEXT | Funn ved ØNH undersøkelse
a|


Kan anvendes til å registrere en tekstlig sammenfatning av en komplett klinisk undersøkelse eller nøkkelfunn ved den kliniske undersøkelsen, som vil bli understøttet av strukturerte data. Dette dataelementet kan brukes for å fange opp "legacy data" som ikke er tilgjengelig i et strukturert format. Detaljer om spesifikt strukturert funn inkluderes ved å bruke CLUSTER-arketyper i "Examination Detail" SLOT.
|====
== Supplerende undersøkelser
== Behov for spesielle undersøkelser fritekst
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Behov for spesielle undersøkelser fritekst* + 
OBSERVATION: _openEHR-EHR-OBSERVATION.progress_note.v1_
|at0004| 0..1| DV_TEXT | Behov for spesielle undersøkelser
a|
5+a|*Reception note metadata dips* + 
CLUSTER: _openEHR-EHR-CLUSTER.reception_note_metadata_dips.v1_
|at0001| 0..*| DV_CODED_TEXT | Datakategori
a|
* at0011 -> Supplerende undersøkelser 
|====
== Vurdering/tiltak
== Vurdering/tiltak
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Vurdering/tiltak* + 
EVALUATION: _openEHR-EHR-EVALUATION.clinical_synopsis.v1_
|at0002| 1..1| DV_TEXT | Vurdering/tiltak
a|
5+a|*Reception note metadata dips* + 
CLUSTER: _openEHR-EHR-CLUSTER.reception_note_metadata_dips.v1_
|at0001| 0..*| DV_CODED_TEXT | Datakategori
a|
* at0012 -> Vurdering 
|at0001| 0..*| DV_CODED_TEXT | Datakategori (2)
a|
* at0013 -> Tiltak 
|====
== Sammendrag
== Sammendrag av innkomst (autogenerert)
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Sammendrag av innkomst (autogenerert)* + 
OBSERVATION: _openEHR-EHR-OBSERVATION.progress_note.v1_
|at0004| 0..1| DV_TEXT | Sammendrag av innkomst (autogenerert)
a|
5+a|*Reception note metadata dips* + 
CLUSTER: _openEHR-EHR-CLUSTER.reception_note_metadata_dips.v1_
|at0001| 0..*| DV_CODED_TEXT | Datakategori
a|
* at0013 -> Tiltak 
|====
== Tidsfestet fritekst
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Tidsfestet fritekst* + 
OBSERVATION: _openEHR-EHR-OBSERVATION.progress_note.v1_
|at0004| 0..1| DV_TEXT | Tidfestet fritekst
a|
|====
// Not supported rmType CODE_PHRASE
// Not supported rmType CODE_PHRASE
// Not supported rmType PARTY_PROXY